---

- name: Create Docker Compose project directory
  file:
    path: /home/{{ docker_user }}/containers
    owner: jangosto
    state: directory
    mode: 0755

- name: Copy the code from repository
  git:
    repo: {{ repository }}
    dest: "/home/{{ docker_user }}/containers/"
    version: {{ repository_version }}

- name: Creates docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ docker_user }}/containers/{{ item }}
  with_items: "{{ enabled_sites }}"
  when: enabled_sites
