---

- name: Create Docker Compose project directory
  file:
    path: /home/{{ docker_user }}/containers
    owner: jangosto
    state: directory
    mode: 0755

- name: Copy the code from repository
  git:
    repo: {{ repository }}
    dest: "/home/{{ docker_user }}/containers/"
    version: {{ repository_version }}

- name: Creates .env file
  template:
    src: env.j2
    dest: /home/{{ docker_user }}/containers/{{ item.site_name }}/.env
  with_items: "{{ sites }}"
  when: sites

- name: Run the service defined in my project
  docker_service:
    project_src: /home/{{ docker_user }}/containers/{{ item.site_name }}
  with_items: "{{ sites }}"
  when: sites
